{
 "title": "Greenplum",
 "description": "Greenplum集群监控状态图",
 "tags": [ "greenplum" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "label_values(greenplum_cluster_state, version)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "gauge",
   "description": "Greenplum截至到当前的运行总时长",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "greenplum_cluster_uptime", "legendFormat": "运行时间" }
   ]
  },
  {
   "title": "版本号",
   "type": "text",
   "description": "Greenplum的版本号",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": {
    "content": "<font size=10><center>$version</center></font>\n\n\n"
   }
  },
  {
   "title": "客户端数",
   "type": "stat",
   "description": "当前数据库的客户端总数（按IP统计）",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_client_count"
    }
   ]
  },
  {
   "title": "账号总数",
   "type": "stat",
   "description": "数据库当前的用户账号总个数",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_server_users_total_count"
    }
   ]
  },
  {
   "title": "Standby同步",
   "type": "gauge",
   "description": "Greenplum集群的Standby节点是否正在保持与Master的同步",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "greenplum_cluster_sync" }
   ]
  },
  {
   "title": "当前连接数",
   "type": "stat",
   "description": "当前连接总数",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_connections"
    }
   ]
  },
  {
   "title": "当前Segment剩余存储空间",
   "type": "stat",
   "description": "Greenplum数据存储节点的剩余可用存储空间(如果有多个数据目录则会显示平均值)",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_node_segment_disk_free_mb_size",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "配置加载时间",
   "type": "stat",
   "description": "数据库配置最近加载时间",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_config_last_load_time_seconds*1000"
    }
   ]
  },
  {
   "title": "在线账号数",
   "type": "stat",
   "description": "当前在线连接的账号总个数",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_total_online_user_count"
    }
   ]
  },
  {
   "title": "Master可达",
   "type": "gauge",
   "description": "Greenplum集群的Master节点是否可连通",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "greenplum_up" }
   ]
  },
  {
   "type": "stat",
   "description": "数据库关注指标",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "greenplum_server_database_hit_cache_percent_rate",
     "legendFormat": "缓存命中率"
    },
    {
     "expr": "greenplum_server_database_transition_commit_percent_rate",
     "legendFormat": "事务提交率"
    }
   ]
  },
  {
   "title": "每个Segment节点总剩余存储空间",
   "type": "stat",
   "description": "Greenplum数据存储节点的剩余可用存储空间(如果有多个数据目录则会显示总数)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_node_segment_disk_sum_free_mb_size",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "活动连接数折线历史图",
   "type": "timeseries",
   "description": "展示各个账号的活动连接数趋势信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_cluster_active_connections",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "每个Segment节点剩余存储空间",
   "type": "bargauge",
   "description": "Greenplum数据存储节点的剩余可用存储空间(每个磁盘单独显示)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_node_segment_disk_sum_device_free_mb_size",
     "legendFormat": "{{hostname}} - {{device}}"
    }
   ]
  },
  {
   "title": "在线账号连接数分析图",
   "type": "timeseries",
   "description": "展示在线账号连接数的历史趋势信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_cluster_active_connections_per_user",
     "legendFormat": "{{usename}}"
    }
   ]
  },
  {
   "title": "客户端连接数统计图",
   "type": "timeseries",
   "description": "展示客户端连接数的历史趋势信息",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_cluster_active_connections_per_client{client!=\"\"}",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "各数据库内表的总数目",
   "type": "timeseries",
   "description": "展示各数据库内表的总数目历史趋势信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_node_database_table_total_count",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "各库存储空间变化图",
   "type": "timeseries",
   "description": "展示各库占用数据存储空间大小的折线图",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "greenplum_node_database_name_mb_size",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "当前各库内表总数目",
   "type": "bargauge",
   "description": "展示集群当前各库内表总数目",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "greenplum_node_database_table_total_count",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "各库存储空间统计图",
   "type": "bargauge",
   "description": "展示当前各库占用数据存储空间大小的柱状图",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_node_database_name_mb_size",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Segment实例在线状态",
   "type": "table",
   "description": "列举集群的Segment实例在线状态",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "greenplum_node_segment_status" }
   ]
  },
  {
   "title": "Segment实例同步模式",
   "type": "table",
   "description": "列举集群的Segment实例同步模式",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "greenplum_node_segment_mode" }
   ]
  },
  {
   "title": "各库耗用存储瞬时速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(greenplum_node_database_name_mb_size[20m])",
     "legendFormat": "{{dbname}}"
    }
   ]
  }
 ]
}